defaults: &defaults
  working_directory: /root/homepage
  docker:
    - image: node:10

version: 2

jobs:
  checkout-and-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/homepage/node_modules
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Lint sources
          command: yarn eslint
      - run:
          name: Run unit tests
          command: yarn test --ci --coverage --colors
      - run:
          name: Upload code-coverage results
          command: yarn stylelint
      - save_cache:
          key: cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/homepage/node_modules

workflows:
  version: 2
  build:
    jobs:
      - checkout-and-test
